sudo: required

services:
  - docker

language: node_js

git:
    submodules: false

env:
  global:
    - GH_REF: github.com/sicilia-io/sicilia-io
    - secure: "h6NgdJXOWiAhQXJruI2FqenibKrQlgFhBWKa1xnQXEdVwDVJi0ByafII0ESdcM/2VohN8ZHwrhJhnCzsnudWTSH46+dSIRONf6O75UKGB9m6ZFAXjxMI3SDm4XHQS/jROgLHTjywzUgmBUfarMewptUMhEv0SviyfheuL6YfOTKfDc49/jZm53CQVOXZEx35glse66JlLCOaGOOnU1AuoMqgk3skmwobgZPix0HzJZRdiiMSOJvxPW0kWPySmM/swE2FffygLiReZ1PN/4CeqXU6D32Ce+vJR8hw5JuS9BLuK384kxH8R8dfhH1rx7ycyN2YF6P9LYmeG9vUb65E2TLbwQiiJ6i0gDqsrW4pBUyEJwYyoZ1hFLpxZM0vphMxXq5JBkAuBXw+P5Ln+nw8aefar9IWhklas4+9QuIZDTGcjDI1DOeBgVbujjqSYsPFq0InY68RlcDUxn2xw1/Y81fz9G8GVaxCAf0NK4xQ/+oPFy6ngaRddthb/d4i9bno/ALBhiQF1MTHQwSZf6pNXzDJzRmQGuFUkJndMboOizkTF+xCEx/ZvoWKKF9XNLfDE8WEbRxhfvL401DnvfYnfkyZYlehqcKgK/AmB1hq+51jLPHRwihAPkZqLIjIYvLbBEmQlFlfk0jC/qjnnHVO09K4AMv5X4aOqXAjQ9Go4ec="

script: make build

after_success:
  - make publish-gh-pages
